"""Toki — adversarial fine-tuning lab for small LLMs."""
from __future__ import annotations

__version__ = "1.11.0"

from toki.generate import AdversarialGenerator
from toki.evaluate import (
    EvaluatorMode,
    GGUFEvaluator,
    HybridScorer,
    RobustnessEvaluator,
    RuleScorer,
    ScoredResult,
)
from toki.safety_lora import (
    LoRATrainResult,
    SafetyLoRAConfig,
    SploraAuditResult,
    freeze_safety_adapter,
    load_safety_subspace,
    splora_audit,
)
from toki.dataset import AdversarialDataset
from toki.experiment import TokiExperiment, ExperimentConfig
from toki.results import ExperimentResult
from toki.benchmark import BenchmarkReport, BenchmarkStats, generate_report
from toki.report import to_json, to_html
from toki.hub import DatasetMetadata, HubUploader, build_dataset_card, write_card
from toki.pipeline import HardeningPipeline, PipelineConfig, PipelineResult, RoundResult
from toki.compare import (
    BASELINES,
    ComparisonConfig,
    ComparisonResult,
    ModelScores,
    ModelSpec,
    compare_models,
)
from toki.ranking import (
    Ranking,
    RankingConfig,
    RankingEntry,
    RankingResult,
)
from toki.leaderboard import (
    Leaderboard,
    LeaderboardEntry,
)
from toki.mutator import (
    PromptMutator,
    MutationConfig,
    MutationResult,
    Individual,
)
from toki.distill import (
    CorpusDistiller,
    DistillConfig,
    DistillResult,
    DistillStats,
)
from toki.integration import (
    EvaluatedRobustnessTest,
    EvaluatedReport,
    EvaluatedItem,
    QualityRubric,
    QualityScores,
    LatencyMetrics,
    has_kairu,
)
from toki.judge import (
    JudgeCriteria,
    CriterionScore,
    JudgeVerdict,
    JudgeConfig,
    JudgeBase,
    MockJudge,
    OllamaJudge,
    AnthropicJudge,
    OpenAIJudge,
    JudgeFactory,
    JudgePipeline,
)
from toki.remediation import (
    RemediationEngine,
    RemediationItem,
    RemediationReport,
    Severity,
)
from toki.attack_library import (
    AttackLibrary,
    CustomAttack,
    VALID_CATEGORIES,
)
from toki.community import (
    CommunityAttack,
    CommunityRegistry,
    filter_attacks as filter_community_attacks,
    get_registry,
    load_bundled,
    load_remote,
)
from toki.campaign import (
    CampaignConfig,
    CampaignResult,
    RedTeamCampaign,
    run_campaign,
)
from toki.coverage import (
    CATEGORY_AXIS,
    ENCODING_AXIS,
    LANGUAGE_AXIS,
    SEVERITY_AXIS,
    CoverageMap,
    compute_coverage,
    label_positions,
)
from toki.regression import (
    Baseline,
    CategoryDelta,
    RegressionReport,
    compare as compare_regression,
)
from toki.consistency import (
    JUDGE_NAMES,
    ConsistencyEntry,
    ConsistencyEvaluator,
    ConsistencyReport,
    fleiss_kappa,
)
from toki.multilingual import (
    ChatInjectGenerator,
    MultilingualGenerator,
    MultilingualPrompt,
    encode_base64,
    encode_rot13,
    encode_zwsp,
    generate_battery,
    generate_chat_inject_battery,
)
from toki.mutation import (
    MutantVariant,
    MutationResult,
    MutationStrategy,
    StrategyMutator,
)
from toki.attack_stats import (
    AttackRecord,
    AttackResult,
    AttackTracker,
)
from toki.exporter import (
    CSV_COLUMNS,
    DatasetExporter,
    ExportFilters,
    parse_filters,
)
from toki.indirect import (
    OWASP_LLM01,
    InjectionScenario,
    IndirectInjectionEvaluator,
    IndirectInjectionGenerator,
    IndirectPrompt,
    InjectionVerdict,
)
from toki.playbook import (
    Playbook,
    PlaybookRunResult,
    PlaybookRunner,
    PlaybookStore,
)
from toki.safety_benchmark import (
    SEVERITY_WEIGHTS,
    BenchmarkDiff,
    BenchmarkRun,
    BenchmarkStore,
    SafetyBenchmark,
    compare_runs,
    compute_safety_score,
    render_report_markdown,
)
from toki.similarity import (
    DedupChecker,
    DedupVerdict,
    TfidfIndex,
    tf,
    tokenize,
)
from toki.agentic import (
    OWASP_MAPPING,
    AgentAttackBattery,
    AgentAttackEvaluator,
    AgentAttackScenario,
    AgentAttackType,
    AgentVerdict,
)
from toki.multiturn import (
    CONV_BASELINES,
    Conversation,
    CrescendoStrategy,
    EchoChamberStrategy,
    MultiTurnConfig,
    MultiTurnResult,
    MultiTurnRunner,
    MultiTurnStrategy,
    Strategy,
    Turn,
    get_strategy,
    run_multiturn,
)
from toki.redteam import (
    DEFENDERS,
    AttackAttempt,
    Attacker,
    DualAgentRedTeam,
    RedTeamConfig,
    RedTeamResult,
    RoundReport,
    run_redteam,
)
from toki.compliance import (
    Control,
    ComplianceReport,
    ControlStatus,
    Framework,
    assess_compliance,
    compliance_from_dataset,
    count_categories,
    get_catalog,
)
from toki.monitor import (
    AlertSink,
    CollectingSink,
    LogSink,
    MonitorConfig,
    MonitorReport,
    ProbeResult,
    SafetyMonitor,
    WebhookSink,
    monitor_once,
)

__all__ = [
    "AdversarialGenerator",
    "EvaluatorMode",
    "GGUFEvaluator",
    "HybridScorer",
    "RobustnessEvaluator",
    "RuleScorer",
    "ScoredResult",
    # Sprint 17 — safety-subspace LoRA
    "LoRATrainResult",
    "SafetyLoRAConfig",
    "SploraAuditResult",
    "freeze_safety_adapter",
    "load_safety_subspace",
    "splora_audit",
    "AdversarialDataset",
    "TokiExperiment",
    "ExperimentConfig",
    "ExperimentResult",
    "BenchmarkReport",
    "BenchmarkStats",
    "generate_report",
    "to_json",
    "to_html",
    "DatasetMetadata",
    "HubUploader",
    "build_dataset_card",
    "write_card",
    "HardeningPipeline",
    "PipelineConfig",
    "PipelineResult",
    "RoundResult",
    "BASELINES",
    "ComparisonConfig",
    "ComparisonResult",
    "ModelScores",
    "ModelSpec",
    "compare_models",
    "Ranking",
    "RankingConfig",
    "RankingEntry",
    "RankingResult",
    "Leaderboard",
    "LeaderboardEntry",
    "PromptMutator",
    "MutationConfig",
    "MutationResult",
    "Individual",
    "CorpusDistiller",
    "DistillConfig",
    "DistillResult",
    "DistillStats",
    "EvaluatedRobustnessTest",
    "EvaluatedReport",
    "EvaluatedItem",
    "QualityRubric",
    "QualityScores",
    "LatencyMetrics",
    "has_kairu",
    "JudgeCriteria",
    "CriterionScore",
    "JudgeVerdict",
    "JudgeConfig",
    "JudgeBase",
    "MockJudge",
    "OllamaJudge",
    "AnthropicJudge",
    "OpenAIJudge",
    "JudgeFactory",
    "JudgePipeline",
    # Phase 14 — Remediation + Real Judges + Attack Library
    "RemediationEngine",
    "RemediationItem",
    "RemediationReport",
    "Severity",
    "AttackLibrary",
    "CustomAttack",
    "VALID_CATEGORIES",
    # Phase 15 — community attack registry
    "CommunityAttack",
    "CommunityRegistry",
    "filter_community_attacks",
    "get_registry",
    "load_bundled",
    "load_remote",
    "CampaignConfig",
    "CampaignResult",
    "RedTeamCampaign",
    "run_campaign",
    # Phase 11 — P1 roadmap
    "CATEGORY_AXIS",
    "ENCODING_AXIS",
    "LANGUAGE_AXIS",
    "SEVERITY_AXIS",
    "CoverageMap",
    "compute_coverage",
    "label_positions",
    "Baseline",
    "CategoryDelta",
    "RegressionReport",
    "compare_regression",
    "JUDGE_NAMES",
    "ConsistencyEntry",
    "ConsistencyEvaluator",
    "ConsistencyReport",
    "fleiss_kappa",
    "MultilingualGenerator",
    "MultilingualPrompt",
    "ChatInjectGenerator",
    "encode_base64",
    "encode_rot13",
    "encode_zwsp",
    "generate_battery",
    "generate_chat_inject_battery",
    # Phase 13 — P2 roadmap
    "OWASP_LLM01",
    "InjectionScenario",
    "IndirectInjectionGenerator",
    "IndirectInjectionEvaluator",
    "IndirectPrompt",
    "InjectionVerdict",
    "OWASP_MAPPING",
    "AgentAttackType",
    "AgentAttackBattery",
    "AgentAttackEvaluator",
    "AgentAttackScenario",
    "AgentVerdict",
    # Phase 14 — playbooks, safety benchmarking, similarity dedup
    "Playbook",
    "PlaybookStore",
    "PlaybookRunner",
    "PlaybookRunResult",
    "SEVERITY_WEIGHTS",
    "BenchmarkRun",
    "BenchmarkDiff",
    "BenchmarkStore",
    "SafetyBenchmark",
    "compute_safety_score",
    "compare_runs",
    "render_report_markdown",
    "tokenize",
    "tf",
    "TfidfIndex",
    "DedupVerdict",
    "DedupChecker",
    # Phase 18 — multi-turn jailbreak engine
    "CONV_BASELINES",
    "Conversation",
    "CrescendoStrategy",
    "EchoChamberStrategy",
    "MultiTurnConfig",
    "MultiTurnResult",
    "MultiTurnRunner",
    "MultiTurnStrategy",
    "Strategy",
    "Turn",
    "get_strategy",
    "run_multiturn",
    # Phase 19 — dual-agent red-team loop
    "DEFENDERS",
    "AttackAttempt",
    "Attacker",
    "DualAgentRedTeam",
    "RedTeamConfig",
    "RedTeamResult",
    "RoundReport",
    "run_redteam",
    # Phase 20 — compliance certification (P3-2)
    "Control",
    "ComplianceReport",
    "ControlStatus",
    "Framework",
    "assess_compliance",
    "compliance_from_dataset",
    "count_categories",
    "get_catalog",
    # Phase 21 — continuous monitoring (P3-5)
    "AlertSink",
    "CollectingSink",
    "LogSink",
    "MonitorConfig",
    "MonitorReport",
    "ProbeResult",
    "SafetyMonitor",
    "WebhookSink",
    "monitor_once",
]
