"""
HuggingFace Hub publishing for adversarial datasets.

Pure-stdlib pieces — ``DatasetMetadata`` and ``build_dataset_card`` — are
importable and testable without any HF dependencies. The actual upload
(``HubUploader.upload`` / ``to_hf_dataset``) requires the ``toki[hf]`` extras
(``datasets`` + ``huggingface_hub``).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from toki import __version__
from toki.dataset import AdversarialDataset


@dataclass
class DatasetMetadata:
    """Metadata embedded in the dataset card and Hub repo.

    Defaults are filled in for every field except ``name`` so that callers
    can construct a fully-valid metadata block with one positional argument.
    """

    name: str
    version: str = "0.1.0"
    description: str = "Adversarial prompts generated by Toki."
    license: str = "BUSL-1.1"
    tags: list[str] = field(
        default_factory=lambda: ["adversarial", "robustness", "safety", "red-team"]
    )
    toki_version: str = __version__
    created: str = ""

    def __post_init__(self) -> None:
        if not self.created:
            self.created = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_dataset_card(stats: dict, metadata: DatasetMetadata) -> str:
    """Render a HuggingFace dataset card (Markdown with YAML frontmatter)."""
    cats: dict[str, int] = stats.get("categories", {})
    total = stats.get("total", 0)

    yaml_tags = "\n".join(f"  - {t}" for t in metadata.tags) or "  - adversarial"
    cat_rows = "\n".join(f"| {c} | {n} |" for c, n in sorted(cats.items())) or "| (none) | 0 |"

    return (
        "---\n"
        "tags:\n"
        f"{yaml_tags}\n"
        f"license: {metadata.license.lower()}\n"
        f"toki_version: {metadata.toki_version}\n"
        f"dataset_version: {metadata.version}\n"
        f"created: {metadata.created}\n"
        "---\n"
        "\n"
        f"# {metadata.name}\n"
        "\n"
        f"{metadata.description}\n"
        "\n"
        "## Statistics\n"
        "\n"
        f"- **Total prompts:** {total}\n"
        "\n"
        "| Category | Count |\n"
        "|----------|-------|\n"
        f"{cat_rows}\n"
        "\n"
        "## Provenance\n"
        "\n"
        f"- Generated by [Toki](https://github.com/wesleyscholl/toki) v{metadata.toki_version}\n"
        f"- Dataset version: `{metadata.version}`\n"
        f"- Created: `{metadata.created}`\n"
        "\n"
        "## License\n"
        "\n"
        f"{metadata.license}\n"
    )


def to_hf_dataset(dataset: AdversarialDataset):
    """Convert an :class:`AdversarialDataset` to a ``datasets.Dataset``.

    Requires ``pip install toki[hf]``.
    """
    try:
        from datasets import Dataset as HFDataset
    except ImportError as exc:
        raise ImportError(
            "Hub upload requires: pip install toki[hf]\n"
            f"Missing: {exc}"
        ) from exc

    records = {
        "text": [p.text for p in dataset],
        "category": [p.category for p in dataset],
        "strategy": [p.strategy for p in dataset],
        "seed": [p.seed for p in dataset],
    }
    return HFDataset.from_dict(records)


class HubUploader:
    """Push an :class:`AdversarialDataset` to the HuggingFace Hub.

    Parameters
    ----------
    repo_id:
        Target repo (``"username/repo-name"``).
    token:
        Hub access token. If ``None``, ``huggingface_hub`` falls back to the
        cached login.
    private:
        Create the repo as private if it does not yet exist.
    """

    def __init__(
        self,
        repo_id: str,
        token: Optional[str] = None,
        private: bool = False,
    ) -> None:
        self.repo_id = repo_id
        self.token = token
        self.private = private

    def upload(
        self,
        dataset: AdversarialDataset,
        metadata: DatasetMetadata,
        commit_message: Optional[str] = None,
    ) -> dict:
        """Create the repo (if needed), push the data, and write the card.

        Returns a summary dict suitable for logging.
        """
        try:
            from huggingface_hub import HfApi
        except ImportError as exc:
            raise ImportError(
                "Hub upload requires: pip install toki[hf]\n"
                f"Missing: {exc}"
            ) from exc

        api = HfApi(token=self.token)
        api.create_repo(
            repo_id=self.repo_id,
            repo_type="dataset",
            private=self.private,
            exist_ok=True,
        )

        hf_ds = to_hf_dataset(dataset)
        push_msg = commit_message or (
            f"Toki v{metadata.toki_version}: dataset {metadata.name} v{metadata.version}"
        )
        hf_ds.push_to_hub(
            self.repo_id,
            token=self.token,
            commit_message=push_msg,
        )

        card = build_dataset_card(dataset.stats(), metadata)
        api.upload_file(
            path_or_fileobj=card.encode("utf-8"),
            path_in_repo="README.md",
            repo_id=self.repo_id,
            repo_type="dataset",
            commit_message=f"Dataset card for {metadata.name} v{metadata.version}",
        )

        return {
            "repo_id": self.repo_id,
            "dataset_version": metadata.version,
            "toki_version": metadata.toki_version,
            "total_prompts": len(dataset),
            "categories": dataset.stats()["categories"],
        }


def write_card(
    dataset: AdversarialDataset,
    metadata: DatasetMetadata,
    path: str | Path,
) -> Path:
    """Write a dataset card to disk for offline review.

    Useful for dry-runs before publishing — generates the same Markdown that
    would be uploaded as ``README.md``.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    card = build_dataset_card(dataset.stats(), metadata)
    path.write_text(card, encoding="utf-8")
    return path
